app = 'invoiceque-web'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  NEXT_PUBLIC_API_URL = 'https://invoicequ-api.invoicequ.workers.dev/api/v1'
  NEXT_PUBLIC_GOOGLE_CLIENT_ID = '84948482130-ft68d81eb0kfgt633qvsor56ihn2a1sh.apps.googleusercontent.com'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 20
    soft_limit = 10

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
