app = 'invoiceque-landing'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

  [build.args]
    NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION = "kzoUcoiaCpXO1DTl95OIT5X3Av4dBRA-Pa2OuJybyQw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 20
    soft_limit = 10

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
